#a=open("f1.txt","x")
#b=open("f2.txt","x")
#c=open("f3.txt","x")
x=open("f1.txt","w")
x.write("hi,good morning")
x.close()
y=open("f2.txt","w")
y.write("how are you")
y.close()
i=open("f1.txt","r")
j=i.read()
i.close()
k=open("f2.txt","r")
l=k.read()
k.close()
m=open("f3.txt","w")
m.write(j + "\n"+l)
m.close()

