import module
print(module.add(8,3))
print(module.sub(5,2))
import math
print(min(2,3,6,1))
print(max(10,45,5,6,79))
print(abs(-5))
print(pow(2,3))
print(math.pi)
print(math.sqrt(25))
print(math.ceil(2.5))
print(math.floor(2.5))
print(math.factorial(5))
print(math.log(2))
print(math.log10(2))
print(math.log2(2))
import datetime
a=datetime.datetime.now()
print(a)
print(a.strftime("%A"))
print(a.strftime("%a"))
print(a.strftime("%B"))
print(a.strftime("%b"))
print(a.strftime("%Y"))
print(a.strftime("%y"))
print(a.strftime("%H"))
print(a.strftime("%M"))
print(a.strftime("%S"))
print(a.strftime("%j"))
b=datetime.date(2002,2,25)
print(b.strftime("%A"))
     