x=("flower","apple",45,"sky","python",2,"sea","desktop","number")
print(x)
print(type(x))
print(len(x))
y=("flower",)
w=("amal","name","india")
print(y)
print(type(y))
print("apple" in x)
print("apple" not in x)
print(x[2])
print(x[2:5])
print(x[3:])
print(x[:5])
print(x[-6:-2])
print(x[-5:])
print(x[:-4])
for i in x:
    print(i)
z=list(x)
print(x)    
z.append("long")
print(z)
z.insert(4,"explore")
print(z)
z.extend(w)
print(z)
z.remove("name")
print(z)
z[1]="mango"
print(z)
z.pop(3)
print(z)
x=tuple(z)
print(x)
e=x+w
print(e)
print(x*2)
print(x.count("explore"))

# practice
a=("edit","select","go","run")
b=("italy","korea","river","malayalam","kerala")
print(a)
print(type(a))
print(len(a))
print("kerala" in a)
print("kerala" not in a)
for i in a:
    print(i)
print(a[3])
print(a[0:2])
print(a[1:])
print(a[:2])
print(b[-2:-1])
print(a[-2:])
print(b[:-2])    
c=list(a)
c.append("type")
print(c)
c.insert(2,"index")
print(c)
c[1]="time"
print(c)
c.remove("go")
print(c)
a=tuple(c)
print(a)
d=a+b
print(d)
e=a*2
print(e)
print(a.count("run"))
